server:
  port: 19020
  servlet:
    context-path: /usm

# eureka
eureka:
  enabled: true
  instance:
    prefer-ip-address: true
    appname: usm
    app-group-name: prometheus
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://seayaa:seayaa@localhost:19080/eureka/eureka/
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 40

# logging
logging:
  level:
    root: info

# database
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prometheus?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: seayaa
    password: seayaa
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  circuitbreaker:
    enabled: true